### ISSUE TITLE
Cancel Menu buttons not attached to corresponding functions

### ISSUE THREAD

**Issue by timFinn** [varygoode/321-project#18]
Main Menu quits the app
Quit calls the cancel menu

**Comment by timFinn** [comment]
Seems that, at the moment, the app states aren't tied to each menu option like in the text-based implementation. Also noticed that there are some lines relating to the quit procedure that have been commented out at Display.java:542

**Comment by varygoode** [comment]
This _should_ be fixed on my next push!
